spring.application.name=Campus-API
spring.profiles.active=mysql
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui-campus.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

#https://www.reddit.com/r/SpringBoot/comments/19dujr8/h2_db_and_mysql/
#https://www.geeksforgeeks.org/advance-java/spring-boot-database-integration-jpa-hibernate-mysql-h2/
#Andere methode om de profiles te maken