DROP DATABASE IF EXISTS campusdb;
CREATE DATABASE campusdb;
USE campusdb;

DROP TABLE IF EXISTS ROOM_RESERVATION;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS APPUSER;
DROP TABLE IF EXISTS CAMPUS;

CREATE TABLE CAMPUS (
    CAMPUS_NAME VARCHAR(255) PRIMARY KEY,
    ADDRESS VARCHAR(255),
    NUMBER_OF_PARKING_SPACES INT,
    NUMBER_OF_ROOMS INT
);

CREATE TABLE ROOM (
    ROOM_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    TYPE VARCHAR(255),
    CAPACITY INT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    FLOOR VARCHAR(255),
    CAMPUS_NAME VARCHAR(255),
    CONSTRAINT FK_ROOM_CAMPUS
    FOREIGN KEY(CAMPUS_NAME) REFERENCES CAMPUS(CAMPUS_NAME)
);

CREATE TABLE APPUSER (
    USER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    DATE_OF_BIRTH DATE
);

CREATE TABLE RESERVATION (
    RESERVATION_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    START_TIME DATETIME,
    END_TIME DATETIME,
    COMMENT VARCHAR(255),
    USER_ID BIGINT,
    CONSTRAINT FK_RESERVATION_USER
        FOREIGN KEY (USER_ID)
        REFERENCES APPUSER(USER_ID)
);

CREATE TABLE ROOM_RESERVATION (
    ROOM_ID BIGINT,
    RESERVATION_ID BIGINT,
    PRIMARY KEY(ROOM_ID, RESERVATION_ID),
    CONSTRAINT FK_RR_ROOM
        FOREIGN KEY (ROOM_ID)
        REFERENCES ROOM(ROOM_ID),
    CONSTRAINT FK_RR_RESERVATION
        FOREIGN KEY (RESERVATION_ID)
        REFERENCES RESERVATION(RESERVATION_ID)
)