DROP TABLE IF EXISTS ROOM_RESERVATION;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS APP_USER;
DROP TABLE IF EXISTS CAMPUS;

CREATE TABLE CAMPUS (
    CAMPUS_NAME VARCHAR(255) PRIMARY KEY,
    ADDRESS VARCHAR(255),
    NUMBER_OF_PARKING_SPACES INT,
    NUMBER_OF_ROOMS INT
);

CREATE TABLE ROOM (
    ROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    TYPE VARCHAR(255),
    CAPACITY INT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    FLOOR VARCHAR(255),
    CAMPUS_NAME VARCHAR(255),
    CONSTRAINT FK_ROOM_CAMPUS
      FOREIGN KEY (CAMPUS_NAME)
          REFERENCES CAMPUS(CAMPUS_NAME)
          ON DELETE CASCADE
);

CREATE TABLE APP_USER (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DATE_OF_BIRTH DATE
);

CREATE TABLE RESERVATION (
    RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    COMMENT VARCHAR(255),
    USER_ID BIGINT,
    CONSTRAINT FK_RESERVATION_USER
     FOREIGN KEY (USER_ID)
         REFERENCES APP_USER(USER_ID)
         ON DELETE CASCADE
);